apiVersion: v1
kind: Service
metadata:
  name: root-service-api
  namespace: sirius
spec:
  selector:
    app: myapp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7003


---
apiVersion: v1
kind: Service
metadata:
  name: root-service-root
  namespace: sirius
spec:
  selector:
    app: myapp-root
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7006

---
apiVersion: v1
kind: Service
metadata:
  name: root-service-info
  namespace: sirius
spec:
  selector:
    app: myapp-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7004


---
apiVersion: v1
kind: Service
metadata:
  name: root-service-login
  namespace: sirius
spec:
  selector:
    app: myapp-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7005